version: '3.7'

services:

  zookeeper1:
    image: zookeeper
    hostname: zookeeper1
    container_name: zookeeper1
    #restart: always
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888

  zookeeper2:
    image: zookeeper
    hostname: zookeeper2
    container_name: zookeeper2
    #restart: always
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zookeeper3:2888:3888

  zookeeper3:
    image: zookeeper
    hostname: zookeeper3
    container_name: zookeeper3
    #restart: always
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=0.0.0.0:2888:3888

  kafka1:
    image: wurstmeister/kafka
    hostname: kafka1
    container_name: kafka1
    #restart: always
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_PORT: 9092
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE1://:9093,OUTSIDE2://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE1:PLAINTEXT,OUTSIDE2:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

  kafka2:
    image: wurstmeister/kafka
    hostname: kafka2
    container_name: kafka2
    #restart: always
    ports:
    - 9093:9092
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_PORT: 9093
        KAFKA_LISTENERS: OUTSIDE1://:9092,INSIDE://:9093,OUTSIDE2://:9094
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE1:PLAINTEXT,OUTSIDE2:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

  kafka3:
    image: wurstmeister/kafka
    hostname: kafka3
    container_name: kafka3
    #restart: always
    ports:
    - 9094:9092
    environment:
        KAFKA_BROKER_ID: 2
        KAFKA_PORT: 9094
        KAFKA_LISTENERS: OUTSIDE1://:9092,OUTSIDE2://:9093,INSIDE://:9094
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE1:PLAINTEXT,OUTSIDE2:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
